apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
# - path: templates/argocd-server/deployment.yaml
#   target:
#     kind: Deployment
#     labelSelector:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-test-argocd-server
    patch: |-
      - op: add
        path: "/metadata/annotations/eks.amazonaws.com~1role-arn"
        value: arn:aws:iam::1234:role/production-role
      - op: add
        path: "/spec/template/metadata/annotations/eks.amazonaws.com~1role-arn"
        value: arn:aws:iam::1234:role/production-role
      - op: add #action
        path: "/spec/template/spec/nodeSelector" #resouirce we want to change
        value:             #value we want to use for patching
          env: prod
          type: spot
          version: "3"

# annotations:
#   example.com/annotation-key: "new-example-value"

helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: "5.41.1"
  releaseName: argo-test
  namespace: argocd-test
  valuesFile: values.yaml
  # valuesInline:
  #   fullnameOverride: argocd-test