apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: "5.41.1"
  releaseName: argo-test
  namespace: argocd-test
  valuesFile: values.yaml
  # valuesInline:
  #   fullnameOverride: argocd-test